using UnityEngine;

public class TODOLIST : MonoBehaviour
{
    //SEPERATE BUILDING SCRIPT (WORKING BUILDING AND BROKEN BUILDING SCRIPT (WIP
    //BUILDING SCRIPT USES TOGGLEUI (CANVAS GROUP TO TRANSPARENT)
    //BROKEN BUILDING USES TOGGLEVISIBILITY (SETACTIVE GAMEOBJECT TO FALSE)
}
